!      SUBROUTINE CALDAY(NYRDAY,     KYEAR,NMON,KALDAY,    MON)
       PROGRAM CALDAY
! **** VERSION OF 03.10.79
!     NYRDAY IS IN THE FORM 'YYDDD'
!     KYEAR,NMON,KALDAY ARE BINARY INTEGER YEAR,MONTH,DAY.  MON IS
!     THE MONTH EXPRESSED IN LEFT-JUSTIFIED THREE-LETTER CODE.
      CHARACTER(len=32) :: arg
      DIMENSION MONTHS(12)
!
      DATA MONTHS/4HJAN ,4HFEB ,4HMAR ,4HAPR ,4HMAY ,4HJUN , 4HJUL ,4HAUG ,4HSEP ,4HOCT ,4HNOV ,4HDEC /
!
       N=IARGC()
      CALL GETARG(1,arg)
      read(arg,*) NYRDAY
      KYEAR = NYRDAY/1000
      JDAY = MOD(NYRDAY,1000)
      JCODE = 1115212
      IF(MOD(KYEAR,4) .EQ. 0) JCODE = 1115208
!
      DO 110 M = 1,12
      MONTH = M
      NDM = 31 - MOD(JCODE,4)
      JDAY = JDAY - NDM
      IF(JDAY .LE. 0) GO TO 120
  110 JCODE = JCODE/4
!
  120 KALDAY = JDAY + NDM
      MON = MONTHS(MONTH)
      NMON = MONTH
      write(6,*) KYEAR,NMON,KALDAY
      END

